spring:
  application:
    name: voting-app
  data:
    mongodb:
      host: localhost
      port: 27017
      database: admin
      username: root
      password: root
  mail:
    host: smtp.gmail.com
    username: sadraquenunesmartiniano2@gmail.com
    password: 'PASSWORD_HERE'
    port: 587
    properties:
      smtp:
        auth: true
        starttls:
          enabled: true
    debug: false
    protocol: smtp
server:
  port: 8080
  error:
    include-stacktrace: never
    include-message: always
    include-binding-errors: always
logging:
  level:
    org.springframework.data.mongodb.repository.query: DEBUG

#routines
routine:
  election:
    open: 60000
    close: 60000

#rabbitmq
rabbit:
  host: http://localhost:15672
  health: /api/health/checks/alarms
  user: guest
  password: guest
  queues:
    vote:
      queue: vote_queue
      exchange: vote_exchange
      routingKey: vote_routing_key
    email:
      queue: email_queue
      exchange: email_exchange
      routingKey: email_routing_key

#security
jwt:
  secret: basic-api-pattern
  expiration: 86400000
password:
  recovery:
    expirationInHour: 1
